### PR TITLE
Added one plugin and updated another

### PR DESCRIPTION
**Pull request by TareHimself**

### CODE REVIEW

**Comment by PapiOphidian** [comment]
The osu plugin as well as the spotify+ plugin have search shorts but don't make use of them. While this doesn't break their functionality, they're totally useless.

**Comment by PapiOphidian** [comment]
The osu plugin package.json also has an incorrect name

**Comment by TareHimself** [comment]
Oh thanks I forgot to remove them and didn't even notice the name thing . Will fix

**Comment by TareHimself** [comment]
Issue fixed

**Pull request merged**
